name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     
      # NODE SETUP
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

     
      # BACKEND
      
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          npm test || echo "No tests found"

   
      # FRONTEND

      - name: Install frontend dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install

      - name: Fix permissions (Linux only)
        run: |
          cd frontend
          chmod -R 755 node_modules/.bin

      - name: Build frontend
        run: |
          cd frontend
          npx react-scripts build